modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]] #mandatory
# The modid of the mod
modId = "bigbrewery" #mandatory
version = "${file.jarVersion}"
displayName = "Big Brewery"
#updateJSONURL=""
#displayURL=""
logoFile="logo.png"
#credits=""
authors = "genericBadName"
displayTest="MATCH_VERSION"
description = '''
Alcoholic innovations using the Create mod.
'''

[[dependencies.bigbrewery]]
modId="forge"
mandatory=true
versionRange="[43.2.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.bigbrewery]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.bigbrewery]]
modId="flywheel"
mandatory=true
versionRange="[0.6.8,0.6.9)"
ordering="AFTER"
side="CLIENT"

[[dependencies.bigbrewery]]
modId="jei"
mandatory=true
versionRange="[11.2.0,11.7.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.bigbrewery]]
modId="curios"
mandatory=true
versionRange="[1.19.2-5.1.1,1.19.2-5.1.5)"
ordering="AFTER"
side="BOTH"

[[dependencies.bigbrewery]]
modId="create"
mandatory=true
versionRange="[0.5.1.b,)"
ordering="NONE"
side="BOTH"